//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebScraper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Dsn=MicrosoftDB.db3;database=C:\\VS_CurrentProjects\\XLP_Capital\\WebScraper\\WebScra" +
            "per\\DB\\MicrosoftDB.db3;stepapi=0;notxn=0;shortnames=0;longnames=0;nocreat=0;nowc" +
            "har=0;fksupport=0;oemcp=0;bigint=0")]
        public string C__VS_CurrentProjects_XLP_Capital_WebScraper_WebScraper_DB_MicrosoftDB_db3ConnectionString {
            get {
                return ((string)(this["C__VS_CurrentProjects_XLP_Capital_WebScraper_WebScraper_DB_MicrosoftDB_db3Connect" +
                    "ionString"]));
            }
        }
    }
}
